apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-cicd
  template:
    metadata:
      labels:
        app: nodejs-cicd
    spec:
      containers:
      - name: nodejs-cicd
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080

