apiVersion: v1
kind: Service
metadata:
  name: nodejs-cicd-service
spec:
  type: NodePort
  selector:
    app: nodejs-cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080

